name: Build and deploy Next.js app to Azure Web App - nodejstest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp -r build/standalone/* deploy/
          cp -r public deploy/ || true
          cp -r build/static deploy/build/ || true
          cp package.json deploy/
          cp package-lock.json deploy/ || true
          cd deploy
          npm install --production
          zip -r ../release.zip .
        env:
          NODE_ENV: production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_757095057A194469A2316B3A2320682A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5840040B9CD34F2B8E189B812613C1EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16E0A67C83014D86A2DB785AC8BF0AFF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nodejstest'
          slot-name: 'Production'
          package: ./deploy