name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          id-token: write
          contents: read
          
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_757095057A194469A2316B3A2320682A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5840040B9CD34F2B8E189B812613C1EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16E0A67C83014D86A2DB785AC8BF0AFF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "nodejstest"
          slot-name: "Production"
          package: ./build/standalone